### ISSUE TITLE
Migrating from webpack 1 to webpack 2

### ISSUE THREAD

**Issue by ksharifbd** [IamMohaiminul/MERNjs#1]
Since, Webpack 2 release is stable and the [documentation](https://webpack.js.org/) is rich, it makes sense to migrate to webpack 2. @IamMohaiminul

**Comment by IamMohaiminul** [comment]
Working on next release. Hope to get this on that release.

**Comment by IamMohaiminul** [comment]
Webpack 2 is implemented in latest commit.
