### ISSUE TITLE
run in server

### ISSUE THREAD

**Issue by alimot22** [IamMohaiminul/MERNjs#2]
i can not run project on server
the error is:

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:C:\Inetpub\vhosts\narinpro.com\webapp.narinpro.com\build\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.

**Comment by IamMohaiminul** [comment]
Before building your app, you can do this in the console:
`export NODE_ENV=production`
Or if you are in windows you could try this:
`SET NODE_ENV=production`

After then you can build and run your app using this:
```
npm run build
npm start
```

**Comment by alimot22** [comment]
not working at production or development.!!
please check your email (IamMohaiminul@gmail.com) i really need some help!

**Comment by IamMohaiminul** [comment]
Yeah, I replied to your email. Please check.
