### ISSUE TITLE
No licensing

### ISSUE THREAD

**Issue by Nicholaiii** [IamMohaiminul/MERNjs#6]
The description of this package is "an open-source full-stack JavaScript solution" but you specify UNLICENSED, explicitly making it not open-source. I highly suggest adopting a license like MIT or GPL-3.0, to open-source the project and allow people to use it freely.

And to clarify, this is straight from the [NPM docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license):
> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
```json
{
  "license": "UNLICENSED"
}
```

**Comment by IamMohaiminul** [comment]
Added the GPL-3.0 license.
